<a href="https://colab.research.google.com/github/jikrey123/data-analysis-journey/blob/main/Dates_and_Time.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

dates = pd.DataFrame({
    "Date": ["2026-01-05", "2026-02-10", "2026-03-15", "2026-04-20"]
})

dates

         Date
0  2026-01-05
1  2026-02-10
2  2026-03-15
3  2026-04-20

In [2]:
#CONVERTING THE COLUMN TO DATE
dates["Date"] = pd.to_datetime(dates["Date"])

In [3]:
#checking the data type
dates.dtypes

Date    datetime64[ns]
dtype: object

In [4]:
#extract the year
dates["Year"] = dates["Date"].dt.year

In [6]:
dates

        Date  Year  Month
0 2026-01-05  2026      1
1 2026-02-10  2026      2
2 2026-03-15  2026      3
3 2026-04-20  2026      4

In [5]:
#extract the month
dates["Month"] = dates["Date"].dt.month

In [7]:
#extract the day
dates["Day"] = dates["Date"].dt.day

In [9]:
#extract the day of the week
dates["Day_Name"] = dates["Date"].dt.day_name()

In [12]:
#extract the month name
dates["Month_Name"] = dates["Date"].dt.month_name()

In [13]:
dates

        Date  Year  Month  Day Day_Name Month_Name
0 2026-01-05  2026      1    5   Monday    January
1 2026-02-10  2026      2   10  Tuesday   February
2 2026-03-15  2026      3   15   Sunday      March
3 2026-04-20  2026      4   20   Monday      April

In [14]:
#creating a more realistic dataset
sales = pd.DataFrame({
    "Date": [
        "2026-01-05",
        "2026-01-15",
        "2026-02-10",
        "2026-02-20",
        "2026-03-05",
        "2026-03-18"
    ],

    "Sales": [100, 150, 200, 180, 250, 300]
})

sales

         Date  Sales
0  2026-01-05    100
1  2026-01-15    150
2  2026-02-10    200
3  2026-02-20    180
4  2026-03-05    250
5  2026-03-18    300

In [27]:
#converting the date column
sales["Date"] = pd.to_datetime(sales["Date"])

In [28]:
#add the month
sales["Month"] = sales["Date"].dt.month_name()

In [29]:
sales

        Date  Sales     Month        Day
0 2026-01-05    100   January     Monday
1 2026-01-15    150   January   Thursday
2 2026-02-10    200  February    Tuesday
3 2026-02-20    180  February     Friday
4 2026-03-05    250     March   Thursday
5 2026-03-18    300     March  Wednesday

In [30]:
#group by month
#this gives us total sales for each month
sales.groupby("Month")["Sales"].sum()

Month
February    380
January     250
March       550
Name: Sales, dtype: int64

In [31]:
#sort the results
#to find the highest_sales month
sales.groupby("Month")["Sales"].sum().sort_values(ascending=False)

Month
March       550
February    380
January     250
Name: Sales, dtype: int64

In [20]:
#group by day of the week
sales["Day"] = sales["Date"].dt.day_name()

In [32]:
sales.groupby("Day")["Sales"].sum().sort_values(ascending=False)

Day
Thursday     400
Wednesday    300
Tuesday      200
Friday       180
Monday       100
Name: Sales, dtype: int64

In [33]:
#finging the difference between dates
start = pd.to_datetime("2026-01-01")
end = pd.to_datetime("2026-01-15")

In [34]:
end - start

Timedelta('14 days 00:00:00')

In [35]:
#filtering by dates
#suppose we want  sales that occured after January 31
sales[sales["Date"]> "2026-01-31"]

        Date  Sales     Month        Day
2 2026-02-10    200  February    Tuesday
3 2026-02-20    180  February     Friday
4 2026-03-05    250     March   Thursday
5 2026-03-18    300     March  Wednesday

In [36]:
#sales during January
sales[sales["Date"].dt.month == 1]

        Date  Sales    Month       Day
0 2026-01-05    100  January    Monday
1 2026-01-15    150  January  Thursday

In [ ]:
[]